module: myeasymocap.stages.basestage.MultiStage
args:
  output: D:/08A4_kgy/emc_output/cam00_full/sv1p
  at_step:
    detect:
      module: myeasymocap.backbone.yolo.yolo.YoloWithTrack
      key_from_data: [images, imgnames]
      args:
        model: yolov5m
        name: person
    keypoints2d:
      module: myeasymocap.backbone.hrnet.myhrnet.MyHRNet
      key_from_data: [images, imgnames]
      key_from_previous: [bbox]
      key_keep: []
      args:
        ckpt: data/models/pose_hrnet_w48_384x288.pth
    vis2d:
      module: myeasymocap.io.vis.Vis2D
      skip: False
      key_from_data: [images]
      key_from_previous: [keypoints, bbox]
      args:
        name: vis_keypoints2d
        scale: 0.5
    infer: # 杩欎釜妯″潡缁欏畾鍥剧墖鍜屾娴嬬殑妗嗭紝鐩存帴杩斿洖crop绯讳笅鐨勪汉浣撳Э鎬?
      module: myeasymocap.backbone.pare.pare.MyPARE
      key_from_data: [images, imgnames] # 浠庢暟鎹泦涓鍏ョ殑bbox銆佸浘鐗囥€佸浘鐗囧悕锛屽浘鐗囧悕鐢ㄤ簬淇濆瓨缁撴灉
      key_from_previous: [bbox]
      key_keep: [cameras, imgnames] # 灏嗚繖浜涘弬鏁伴兘淇濈暀鍒版渶鍚庣殑杈撳嚭涓?
      args:
        ckpt: 3dpw # 鎸囧畾浣跨敤3dpw鐨勯璁粌妯″瀷
  at_final:
    load_body_model: # 杞藉叆SMPL妯″瀷
      module: myeasymocap.io.model.SMPLLoader
      args:
        model_path: models/pare/data/body_models/smpl/SMPL_NEUTRAL.pkl
        regressor_path: models/J_regressor_body25.npy
    init_translation: # 缁欏畾crop绯讳笅鐨勫Э鎬併€?D鍏抽敭鐐广€佺浉鏈哄弬鏁帮紝杩斿洖涓栫晫绯讳笅鐨勪汉浣撳Э鎬?
      module: myeasymocap.operations.init.InitTranslation
      key_from_data: [keypoints, cameras, params] # 璇诲叆鍏抽敭鐐广€佺浉鏈哄弬鏁般€丼MPL鍙傛暟
      key_from_previous: [body_model] # 璇诲叆SMPL妯″瀷杩涜鍏抽敭鐐硅绠?
      args:
        solve_T: True
        solve_R: False
    smooth: # 瀵瑰垵濮嬪寲鐨勭粨鏋滆繘琛屽钩婊?
      module: myeasymocap.operations.smooth.SmoothPoses
      key_from_data: [params]
      args:
        window_size: 2
    mean_param: # Mean shapes
      module: myeasymocap.operations.init.MeanShapes
      key_from_data: [params]
      args:
        keys: ['shapes']
    init_RT:
      module: myeasymocap.operations.optimizer.Optimizer
      key_from_data: [keypoints, cameras]
      key_from_previous: [model, params]
      args:
        optimizer_args: {optim_type: lbfgs}
        optimize_keys: [Th, Rh]
        loss:
          repro:
            weight: 100.
            module: myeasymocap.operations.loss.Keypoints2D
            key_from_output: [keypoints]
            key_from_infos: [keypoints, cameras]
            args:
              norm: l2
              index_est: [2, 5, 9, 12]
              index_gt: [2, 5, 9, 12]
          smooth:
            weight: 1.
            module: myeasymocap.operations.loss.Smooth
            key_from_output: [Rh, Th]
            key_from_infos: [cameras] # TODO: 鏍规嵁2D鐨勭疆淇″害鏉ヨ绠梥mooth鏉冮噸
            args:
              keys: [Th, Th]
              smooth_type: [Linear, Depth] # 杩欎釜depth浼间箮闇€瑕佺浉鏈哄弬鏁拌繘琛岃浆鎹?
              norm: [l2, l2]
              order: [2, 2]
              weights: [100., 1000.]
              window_weight: [0.5, 0.3, 0.1, 0.1]
    refine_poses:
      repeat: 2
      module: myeasymocap.operations.optimizer.Optimizer
      key_from_data: [keypoints, cameras]
      key_from_previous: [model, params]
      args:
        optimizer_args: {optim_type: lbfgs}
        optimize_keys: [poses, Rh, Th]
        loss:
          repro:
            weight: 100.
            module: myeasymocap.operations.loss.Keypoints2D
            key_from_output: [keypoints]
            key_from_infos: [keypoints, cameras]
            args:
              norm: gm
              norm_info: 0.02
          smooth:
            weight: 1.
            module: myeasymocap.operations.loss.Smooth
            key_from_output: [poses, Rh, Th, keypoints]
            key_from_infos: [cameras] # TODO: 鏍规嵁2D鐨勭疆淇″害鏉ヨ绠梥mooth鏉冮噸
            args:
              keys: [Th, Th, poses, keypoints]
              smooth_type: [Linear, Depth, Linear, Linear] # 杩欎釜depth浼间箮闇€瑕佺浉鏈哄弬鏁拌繘琛岃浆鎹?
              norm: [l2, l2, l2, l2]
              order: [2, 2, 2, 2]
              weights: [100., 1000., 50., 100.]
              window_weight: [0.5, 0.3, 0.1, 0.1]
          init:
            weight: 1.
            module: myeasymocap.operations.loss.Init
            key_from_output: [poses]
            key_from_infos: [init_poses]
            args:
              keys: [poses]
              norm: l2
              weights: [1.]
          prior:
            weight: 0.1
            module: easymocap.multistage.gmm.GMMPrior
            key_from_output: [poses]
            key_from_infos: []
            args:
              start: 0
              end: 69
    write:
      module: myeasymocap.io.write.WriteSMPL
      key_from_data: [meta]
      key_from_previous: [params, model]
      args:
        name: smpl
    render:
      module: myeasymocap.io.vis3d.Render
      key_from_data: [cameras, imgnames]
      key_from_previous: [params, body_model]
      args:
        backend: pyrender
    make_video:
      module: myeasymocap.io.video.MakeVideo
      args:
        fps: 30
        keep_image: True
